### ISSUE TITLE
Support Layouts with Both Splits and Tabs

### ISSUE THREAD

**Issue by cheyngoodman** [BiagioFesta/i3-autolayout#13]
I'm hoping this can be updated to allow both tabs and splits in the same layout.

Specifically to allow a main window that is tiled to the left, while all other windows are tabbed in a window to the right side of the main window.

**Comment by BiagioFesta** [comment]
That's interesting.

Generally speaking, i3-autolayout tries to be as less intrusive as possible. So actions on i3 are transparent.

I think you can already achieve the layout you are describing.
* Go on an empty workspace.
* Open an application.
* Mod+W (or whatever is your binding) to switch to tabbed mod.
* Open multiple application/windows.
* Focus on window and use Mod+right-arrow (or whatever is your bindings) to move the focused window outside the tabbed layout.

**Comment by cheyngoodman** [comment]
Thank you for explaining! I mistakenly rebound `i3-msg layout tabbed` to `i3-autolayout tabmode`.

After reverting the change and testing your steps, I can achieve the workflow I was hoping for.
