### ISSUE TITLE
i3-autolayout crashes every few minutes.

### ISSUE THREAD

**Issue by yatinlala** [BiagioFesta/i3-autolayout#2]
The title pretty much explains my issue. Here is the [backtrace](https://github.com/BiagioFesta/i3-autolayout/files/9181798/backtrace.txt) I've been getting. Please let me know if there is anything I can do or provide to help solve this issue.
 
Thank you so much for the wonderful project!

**Comment by BiagioFesta** [comment]
Hi,
Thank you for the feedback and for opening the issue.

I will investigate as soon as possible.

In the meanwhile, could please provide me the version/commit you are using?
 * Have you compiled the binary from the source code base, or used `cargo install`?

**Comment by yatinlala** [comment]
I am using v0.2.0, installed via `cargo install`.

**Comment by BiagioFesta** [comment]
Could you please provide me the version of the i3wm you are using?

I.e., ```i3 --version``` (and if you are using some fork, e.g., `i3-gaps`)

Thanks

**Comment by yatinlala** [comment]
I'm using i3-gaps, on ArchLinux. Kernel is `5.18.14-arch1-1`
`i3 version 4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors`

**Comment by BiagioFesta** [comment]
Thank you very much.

Because of your report, I think I have been able to identify a data-race issue and fix it.

I have also leveraged this opportunity to make some refinements to the code.

I have merged the patch and published a new release: [`i3-autolayout@v0.2.1`](https://github.com/BiagioFesta/i3-autolayout/releases/tag/v0.2.1)

It might be sufficient to do a simple `cargo install i3-autolayout` to fetch the latest release.
Just be sure there are no other-older `i3-autolayout` instances running.

I am going to leave this issue open, please let me know if this hot-fix solves your issue; in that case, feel free to close it.

**Comment by yatinlala** [comment]
I appreciate the quick turnaround!

The PR doesn't seem to have fixed my issue.

I've investigated the problem some more, and I'm noticing that moving windows to scratchpad is causing the crashes. v.0.2.1 is providing a new error though:

```
Creating event listener...
  Ok
Creating command executor...
  Ok
Error: Failure in command 'autolayout'

Caused by:
    Cannot find parent of focused window
```

**Comment by BiagioFesta** [comment]
Thank you for your feedback.

I've opened another small PR. 

Before creating a new release, it would be really helpful if you might find some time to quickly try the patch.

- Kill running instances of `i3-autolayout`, if any.

```
git clone --branch dev/floating-fix https://github.com/BiagioFesta/i3-autolayout.git && \
cd i3-autolayout && \
cargo run --release -- autolayout
```

This will clone the source code with the patch and it compiles the binary. It requires having `cargo`/ rust compiler installed. If you have any issue please let me know.

Afterwards, you can simply remove the directory `i3-autolayout` to cleanup (the binary will be compiled inside the cloned directory).

Thank you in advance

**Comment by yatinlala** [comment]
It appears to work! Thanks again for your help.

**Comment by BiagioFesta** [comment]
All right! 

Now it is quite late in my local time, but I am going to create another patch release tomorrow (a matter of hours) with this latter fix.

So you should be able to upgrade and finally work with `i3-autolayout` :)

Thank you again for your report, it allowed me to effectively improve the code.

For any other issue or feature request, do not hesitate to open another issue here on GitHub. Thanks

**Comment by BiagioFesta** [comment]
I've published a new release: https://github.com/BiagioFesta/i3-autolayout/releases/tag/v0.2.2

Hopefully, this is going to fix all the issues.

Feel free to upgrade to the latest release and close this issue if everything works for you.
